### ISSUE TITLE
feat: Implement voting history page

### ISSUE THREAD

**Issue by clockworkgr** [allinbits/govgen-governance-dapp#66]
A page where the user can review his past voting behavior across the chain's proposals.

May include multiple vote casts for a single proposal so should flag the latest/valid vote as well as the previous overridden ones

**Comment by AidarItkulov** [comment]
Needs reviewing:
https://www.figma.com/file/HQLnOao5FDl7iwS0O4F891/Governance-Platform?type=design&node-id=28012%3A8866&mode=design&t=FcIKkWxiRN94OhLV-1
